### ISSUE TITLE
cannot compile with ghc-8.8 because ‘fail’ is not a (visible) method of class ‘Monad’

### ISSUE THREAD

**Issue by jwaldmann** [nominolo/atto-lisp#24]
```
...
atto-lisp    > [1 of 1] Compiling Data.AttoLisp
atto-lisp    > 
atto-lisp    > /tmp/stack-7e4284eec0adb234/atto-lisp-0.2.2.3/Data/AttoLisp.hs:132:5: error:
atto-lisp    >     ‘fail’ is not a (visible) method of class ‘Monad’
atto-lisp    >     |
atto-lisp    > 132 |     fail msg = Parser $ \kf _ks -> kf msg
atto-lisp    >     |     ^^^^
atto-lisp    > 
```
